services:
  flytsim:
    build: .
    command: sudo /start.sh Linux
    container_name: flytsim
    devices:
    - /dev/nvidia0
    - /dev/nvidiactl
    - /dev/nvidia-uvm
    environment:
    - DISPLAY
    - QT_X11_NO_MITSHM=1
    hostname: flytsim
    labels:
      com.nvidia.volumes.needed: nvidia_driver
    ports:
    - 80:80
    - 5760:5760
    - 8080:8080
    privileged: true
    user: flytsim
    volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - flytsim:/flyt
    - /run/udev:/run/udev:ro
    - nvidia_driver_378.13:/usr/local/nvidia:ro
    working_dir: /home/flytsim
version: '3'
volumes:
  flytsim: null
  nvidia_driver_378.13:
    external: true
